### ISSUE TITLE
渲染后锯齿有点严重呀

### ISSUE THREAD

**Issue by crawt** [NumerHero/animations#4]
看着canvas的方案还不够完美

**Comment by bilibiliou** [comment]
关于这个这个问题，我是想了怎么解决

一个解决方案是放大n 倍再缩小n 倍，但是无效果

另外一个是调用canvas 下的一个api来解决锯齿，依然无效果

不知道您又没有什么好的解决方案？

**Comment by crawt** [comment]
暂时也没有好的方案，我之前做类似的功能也遇到这个问题，最后是用svg解决的

**Comment by bilibiliou** [comment]
Svg 下的实现描边动画很简单
但是Canvas 就不行了

echart 官网上的描边动画就是基于canvas 的，不知道他们如何处理锯齿的

**Comment by hqzh** [comment]
大佬svg实现demo也上传下呗@crawt

**Comment by bilibiliou** [comment]
@hqzh 请问您指的是那个动画？

**Comment by bilibiliou** [comment]
锯齿的解决方案，最近意识到怎么解决了。
<canvas> winth 和 height 跟父级走，父级 宽和高 设为两倍，然后再用translate(-50%, -50%) 缩小

**Comment by bilibiliou** [comment]
具体缩小几倍由精度决定，但是两倍缩放下，锯齿已经差不多解决了
但是存在的问题是，放大两倍后会占据原有的文档流

**Comment by hqzh** [comment]
@NumerHero 水球那个动画!

**Comment by hqzh** [comment]
@NumerHero 如何让波浪覆盖整个圆圈啊

**Comment by bilibiliou** [comment]
@hqzh  

[教程](https://www.w3cplus.com/animations/water-bubble.html)

覆盖整个圆圈很简单，把 两个半径调整成一样就好啦

**Comment by hqzh** [comment]
![water](https://user-images.githubusercontent.com/26128706/45356719-adf69200-b5f6-11e8-920f-bd259f793bf7.png)
@NumerHero 设成ctx.arc(r, r, bR -  lineWidth, 0, 2 * PI, 1);是填满了但是有锯齿

**Comment by bilibiliou** [comment]
@hqzh  有锯齿是正常的 上面已经说了，通过 css 调整

**Comment by hqzh** [comment]
@NumerHero thank you so much

**Comment by bilibiliou** [comment]
@hqzh 给个star就行
